// <auto-generated />
using Ganges.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(GangesDbContext))]
    [Migration("20200806112312_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("Ganges.ApplicationCore.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Seller")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Plastic",
                            ImageUrl = "toy.png",
                            Price = 50,
                            Quantity = 2,
                            Seller = "Michael",
                            Title = "Toy"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hard back",
                            ImageUrl = "book.png",
                            Price = 25,
                            Quantity = 4,
                            Seller = "Peter",
                            Title = "Book"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bright",
                            ImageUrl = "lamp.png",
                            Price = 75,
                            Quantity = 1,
                            Seller = "David",
                            Title = "Lamp"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
