// <auto-generated />
using Ganges;
using Ganges.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ganges.Migrations
{
    [DbContext(typeof(GangesDbContext))]
    [Migration("20200601094415_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ganges.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Seller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Glass",
                            ImageUrl = "table.png",
                            Price = 100,
                            Quantity = 2,
                            Seller = "George",
                            Title = "Table"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Wooden",
                            ImageUrl = "chair.png",
                            Price = 50,
                            Quantity = 5,
                            Seller = "Kevin",
                            Title = "Chair"
                        },
                        new
                        {
                            Id = 3,
                            Description = "High performance",
                            ImageUrl = "computer.png",
                            Price = 800,
                            Quantity = 1,
                            Seller = "James",
                            Title = "Computer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
